### PR TITLE
Fix Try Catch Failure

### PR DESCRIPTION
**Pull request by The-Don-Himself**
Should Fix 
https://github.com/PommeVerte/gremlin-php/issues/37

### CODE REVIEW

**Comment by PommeVerte** [comment]
Hey thanks a lot 
There's no harm in adding this change but could you let me know how I could recreate the issue that this solves? I would like to take a closer look at it. 

I can't seem to recreate it myself. 
Linux dist and version?
Composer version?
PHP 7.1.? ?

Also if you wouldn't mind rebasing this :) If not it's ok I can just apply these changes manually.

Cheers

**Comment by The-Don-Himself** [comment]
Hey @PommeVerte  not problem, sorry for not including the particulars, it should be standard practice to do so.

I can reproduce this both on my dev laptop and a production server, latest PHP and composer i.e
Windows 7 x64
PHP - 7.1.8
Composer 1.5.1

and prod
Centos 7.3
PHP - 7.1.8
Composer 1.5.1

To reproduce, try setting host variable on Connection to an IP you know doesn't host a running JanusGraph server. The exception can't be caught but the fix in the PR makes it caught so don't know whether is a gremlin-php thing or a bug in the greater PHP itself.

**Comment by The-Don-Himself** [comment]
> Also if you wouldn't mind rebasing this :) If not it's ok I can just apply these changes manually.

Perhaps you could just apply the changes, I had never rebased before (mostly work on small projects) so when I started looking into it and tried creating upstream branches and I kinda got lost :(

**Comment by PommeVerte** [comment]
ok no problem I'll do that. 
Cheers. 

I'll let you know if I can recreate and why this happens.

**Comment by The-Don-Himself** [comment]
Thanks, will appreciate that.
Guess I can close this then?

**Comment by PommeVerte** [comment]
Yep.
BTW as an FYI the rebase might've been complicated because you worked directly on the "master" branch of your fork. It's always better to make a separate branch for your PRs :) 
Then you can just make sure your master is in sync with the master from this repo and go to your separate branch and do `git rebase master`
Cheers.

**Comment by The-Don-Himself** [comment]
Thanks I dint know that. Will try that for any other PRs that may come up. Was actually wanting to do one for https://github.com/PommeVerte/gremlin-php/issues/34 but I see you fixed that :+1:

**Pull request closed without merging**
